/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedNotesNoteIdRouteImport } from './routes/_authenticated/notes.$noteId'
import { Route as AuthenticatedShopCategoryRouteImport } from './routes/_authenticated/shop.$category'
import { Route as AuthenticatedShopCategoryProductIdRouteImport } from './routes/_authenticated/shop.$category.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesNoteIdRoute =
  AuthenticatedNotesNoteIdRouteImport.update({
    id: '/$noteId',
    path: '/$noteId',
    getParentRoute: () => AuthenticatedNotesRoute,
  } as any)
const AuthenticatedShopCategoryRoute =
  AuthenticatedShopCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => AuthenticatedShopRoute,
  } as any)
const AuthenticatedShopCategoryProductIdRoute =
  AuthenticatedShopCategoryProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedShopCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/cart': typeof AuthenticatedCartRoute
  '/chat': typeof AuthenticatedChatRoute
  '/notes': typeof AuthenticatedNotesRouteWithChildren
  '/shop': typeof AuthenticatedShopRouteWithChildren
  '/social': typeof AuthenticatedSocialRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/shop/$category': typeof AuthenticatedShopCategoryRouteWithChildren
  '/shop/$category/$productId': typeof AuthenticatedShopCategoryProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/cart': typeof AuthenticatedCartRoute
  '/chat': typeof AuthenticatedChatRoute
  '/notes': typeof AuthenticatedNotesRouteWithChildren
  '/shop': typeof AuthenticatedShopRouteWithChildren
  '/social': typeof AuthenticatedSocialRoute
  '/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/shop/$category': typeof AuthenticatedShopCategoryRouteWithChildren
  '/shop/$category/$productId': typeof AuthenticatedShopCategoryProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRouteWithChildren
  '/_authenticated/shop': typeof AuthenticatedShopRouteWithChildren
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/notes/$noteId': typeof AuthenticatedNotesNoteIdRoute
  '/_authenticated/shop/$category': typeof AuthenticatedShopCategoryRouteWithChildren
  '/_authenticated/shop/$category/$productId': typeof AuthenticatedShopCategoryProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/calendar'
    | '/cart'
    | '/chat'
    | '/notes'
    | '/shop'
    | '/social'
    | '/notes/$noteId'
    | '/shop/$category'
    | '/shop/$category/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/calendar'
    | '/cart'
    | '/chat'
    | '/notes'
    | '/shop'
    | '/social'
    | '/notes/$noteId'
    | '/shop/$category'
    | '/shop/$category/$productId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/settings'
    | '/_authenticated/calendar'
    | '/_authenticated/cart'
    | '/_authenticated/chat'
    | '/_authenticated/notes'
    | '/_authenticated/shop'
    | '/_authenticated/social'
    | '/_authenticated/notes/$noteId'
    | '/_authenticated/shop/$category'
    | '/_authenticated/shop/$category/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/$noteId': {
      id: '/_authenticated/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AuthenticatedNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedNotesRoute
    }
    '/_authenticated/shop/$category': {
      id: '/_authenticated/shop/$category'
      path: '/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof AuthenticatedShopCategoryRouteImport
      parentRoute: typeof AuthenticatedShopRoute
    }
    '/_authenticated/shop/$category/$productId': {
      id: '/_authenticated/shop/$category/$productId'
      path: '/$productId'
      fullPath: '/shop/$category/$productId'
      preLoaderRoute: typeof AuthenticatedShopCategoryProductIdRouteImport
      parentRoute: typeof AuthenticatedShopCategoryRoute
    }
  }
}

interface AuthenticatedNotesRouteChildren {
  AuthenticatedNotesNoteIdRoute: typeof AuthenticatedNotesNoteIdRoute
}

const AuthenticatedNotesRouteChildren: AuthenticatedNotesRouteChildren = {
  AuthenticatedNotesNoteIdRoute: AuthenticatedNotesNoteIdRoute,
}

const AuthenticatedNotesRouteWithChildren =
  AuthenticatedNotesRoute._addFileChildren(AuthenticatedNotesRouteChildren)

interface AuthenticatedShopCategoryRouteChildren {
  AuthenticatedShopCategoryProductIdRoute: typeof AuthenticatedShopCategoryProductIdRoute
}

const AuthenticatedShopCategoryRouteChildren: AuthenticatedShopCategoryRouteChildren =
  {
    AuthenticatedShopCategoryProductIdRoute:
      AuthenticatedShopCategoryProductIdRoute,
  }

const AuthenticatedShopCategoryRouteWithChildren =
  AuthenticatedShopCategoryRoute._addFileChildren(
    AuthenticatedShopCategoryRouteChildren,
  )

interface AuthenticatedShopRouteChildren {
  AuthenticatedShopCategoryRoute: typeof AuthenticatedShopCategoryRouteWithChildren
}

const AuthenticatedShopRouteChildren: AuthenticatedShopRouteChildren = {
  AuthenticatedShopCategoryRoute: AuthenticatedShopCategoryRouteWithChildren,
}

const AuthenticatedShopRouteWithChildren =
  AuthenticatedShopRoute._addFileChildren(AuthenticatedShopRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRouteWithChildren
  AuthenticatedShopRoute: typeof AuthenticatedShopRouteWithChildren
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRouteWithChildren,
  AuthenticatedShopRoute: AuthenticatedShopRouteWithChildren,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
